main:
  production_name: Birthday-Calendar

production:
  name: birthday calendar
  days:
    - title: test
      date: "2020-01-25"
      offset: 3
      solar: true
    - title: 我的阳历生日
      date: "1993-06-27"
      offset: 2
      solar: true
    - title: 我的阴历生日
      date: "1993-05-08"
      offset: 30
      solar: false


