main:
  production_name: Birthday-Calendar

production:
  name: birthday calendar
  days:
    - title: test
      date: "2020-01-25"
      offset: 3
      solar: true
    - title: my birthday
      date: "1993-01-26"
      offset: 4
      solar: true
    - title: future day test
      date: "2222-01-01"
      offset: 30
      solar: false


